title: Justin Johnson # your name (or website title) here
logo: "GESFinalProject.io/images/IMG-3547.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Graduate Student</strong> at University of Maryland, Baltimore County. 
  <br><br>
  <strong>Mapping Single-Family Zoning In Central Maryland</strong>: Measuring how widespread single-family zoning restrictions are in the Baltimore Metropolitan Statisitcal Area.
  

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
