title: Justin Johnson # your name (or website title) here
logo: "images/IMG-3547.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <strong>Graduate Student in Economic Policy Analysis</strong> at University of Maryland, Baltimore County. 

  



theme: jekyll-theme-minimal
