title: Justin Johnson 
logo: "images/IMG-3547.jpg" 
description: > 
 <strong>Graduate Student in Economic Policy Analysis</strong> at University of Maryland, Baltimore County. 

  



theme: jekyll-theme-minimal
